language: scala
sudo: false
branches:
  only:
    - master
    - release
    - /^\d\.\d+$/
jdk:
- oraclejdk8
scala:
- 2.13.0
dist: trusty
script:
  - sbt test
cache:
  directories:
    - $HOME/.sbt
before_cache:
  - find $HOME/.sbt        -name "*.lock"               -print -delete